const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

async function run() {
    const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL,
        process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    
    // The exact apps generated by the user that we want to keep
    const keepAppIds = [
        '627e145d-e609-475d-a4cd-228c15c7b2a5', // Piggy Bank New
        'df45d1bf-0f21-4ee2-9375-a839f795b930'  // Piggy Bank (verified)
    ];

    const { data: apps, error } = await supabase.from('apps').select('id, name');
    if (error) {
        console.error("Fetch error:", error);
        return;
    }
    
    let deletedCount = 0;
    for (const app of apps) {
        if (!keepAppIds.includes(app.id)) {
            console.log(`Deleting duplicate test app: ${app.name} (${app.id})`);
            await supabase.from('apps').delete().eq('id', app.id);
            deletedCount++;
        }
    }
    console.log(`Successfully purged ${deletedCount} fake test miniapps.`);
}
run();
