const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

async function run() {
    console.log("Connecting to Production Database...");

    // 1. Delete Phantom E2E Apps
    const { data: apps } = await supabase.from('apps').select('id, domain').eq('domain', 'https://openads.xyz');
    if (apps && apps.length > 0) {
        for (const app of apps) {
            console.log(`Deleting Phantom App: ${app.domain} (ID: ${app.id})`);
            await supabase.from('apps').delete().eq('id', app.id);
        }
    }

    // 2. Eradicate E2E Telemetry from tracking_events (Impressions/Clicks)
    // This purges all the 46 impressions generated by the local headless Chromium tests
    console.log("Purging headless Chromium telemetry logs...");
    const r1 = await supabase.from('tracking_events').delete().eq('parent_url', 'https://openads.xyz');
    const r2 = await supabase.from('tracking_events').delete().like('parent_url', '%localhost%');
    console.log("Localhost telemetry purged.", r2.count || '');

    console.log("Database scrubbing complete. Live Dashboard should now reflect true organic volume.");
}

run().catch(console.error);
