require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');
const fetch = require('node-fetch');

async function testAuth() {
    // 1. Emulate the EXACT payload generated by Farcaster fcClient.watchStatus in landing.js
    const mockAuthObj = {
        role: "advertiser",
        provider: "farcaster",
        username: "fc_user_12345",
        fid: "12345",
        address: "0xMockCustodyAddress123",
        signature: "0xMockSignatureThatWillFailVerificationButPassJSONParse",
        nonce: "MockNoncexyz",
        message: "openads-backend.vercel.app wants you to sign in with your Ethereum account:\n0xMockCustodyAddress123\n\nFarcaster Auth\n\nURI: https://openads-backend.vercel.app\nVersion: 1\nChain ID: 10\nNonce: MockNoncexyz\nIssued At: 2024-03-24T00:00:00.000Z",
        socialVerified: true,
        loggedAt: Date.now(),
        siwf: "live"
    };

    // 2. Emulate the authHeaderRaw (the raw string inside localStorage 'openads_auth')
    const authHeaderRaw = JSON.stringify(mockAuthObj);
    
    // 3. Emulate app.js fetchCampaignHistory base64 engine
    let authBase64 = '';
    try {
        authBase64 = Buffer.from(unescape(encodeURIComponent(authHeaderRaw))).toString('base64');
    } catch (e) {
        console.warn('Failed to encode:', e);
    }
    
    // 4. Emulate my-campaigns.html advWallet resolution
    let advWallet = '';
    const parsedObj = JSON.parse(authHeaderRaw);
    if (parsedObj.role === 'advertiser') {
         advWallet = parsedObj.provider === 'farcaster' ? String(parsedObj.fid) : (parsedObj.address || String(parsedObj.fid));
    }
    
    console.log("Resolved advWallet param:", advWallet);
    console.log("Resolved X-OpenAds-Auth format valid Base64?:", /^[A-Za-z0-9+/=]+$/.test(authBase64));

    // 5. Fire against LOCAL backend to test 
    const url = `http://localhost:3000/api/v1/user/campaigns?wallet=${advWallet}`;
    console.log(`Fetching: ${url}`);
    
    try {
        const res = await fetch(url, {
            headers: { 'X-OpenAds-Auth': authBase64 }
        });
        
        const text = await res.text();
        console.log(`HTTP Status: ${res.status}`);
        console.log(`Response Body: ${text}`);
    } catch (err) {
        console.error("Fetch failed:", err);
    }
}
testAuth();
